title: OneShot Short URLs
description: Short URLs for OneShot Discord.
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: hlaueriksson/jekyll-url-shortener
